### ISSUE TITLE
Inappropriate use of the arduino-library topic

### ISSUE THREAD

**Issue by per1234** [gedankenlab/Kaleidoglyph-Glukeys#3]
This repository is not an Arduino library, thus the use of the `arduino-library` topic is inappropriate.

The topic can be removed by clicking the "Manage topics" link near the top of the repository's home page and then clicking the X to the right of `arduino-library`.

**Comment by gedankenexperimenter** [comment]
It's a placeholder at the moment.

Your attitude is very aggressive. I suggest trying to be friendlier when communicating with strangers for the first time.

**Comment by per1234** [comment]
>It's a placeholder at the moment.

Why not wait until you actually have an Arduino library in the repository to advertise it as such? Topics are used to make your repository more discoverable, so what's the point of making a repository that has sat empty for months discoverable.

>Your attitude is very aggressive. I suggest trying to be friendlier when communicating with strangers for the first time.

I'm sorry if that's the way you interpreted it. That wasn't at all my intention. I'm merely stating facts in as succinct a manner as possible. I welcome any specific suggestions for how I can reword this text in the future when I'm doing further work to clean up the `arduino-libraries` topic.
